# Generated by Django 3.1.4 on 2020-12-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('frontback', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('commentsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.comment')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.user')),
            ],
            options={
                'db_table': 'roadmaps',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='roadmapid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmap'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.user'),
        ),
    ]
