# Generated by Django 3.1.4 on 2020-12-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '__first__'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='roadmapid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmap'),
        ),
    ]
